[package]
name = "xxd"
version = "0.1.0"
authors = ["Nicola Coretti <nico.coretti@gmail.com>"]
edition = "2018"

[lib]
name = "xxd"
path = "src/lib.rs"

[[bin]]
name = "dump"
path = "src/bin/main.rs"

[dependencies]
yansi = "0.5.0"
structopt = "0.3.21"
anyhow = "1.0.40"
human-panic = "1.0.3"
