alias b := build
alias c := check
alias f := fix
alias m := mypy
alias t := test

build:
    uv build

test *args:
    uv run pytest test {{ args }}

fmt *args:
    uv run ruff format src test {{ args }}

fix *args:
    uv run ruff format src test
    uv run ruff check --fix src test

check *args:
    uv run ruff check src test {{ args }}

mypy *args:
    uv run mypy konfy {{ args }}
