alias b := build
alias c := check
alias f := fix
alias m := type-check
alias t := test

default:
    just --list

build:
    uv build

[group('python')]
test *args:
    uv run pytest python/test {{ args }}

[group('python')]
fix *args:
    uv run ruff check --fix --show-fixes python/src python/test {{ args }}

[group('python')]
check *args:
    uv run ruff check python/src python/test {{ args }}

[group('python')]
type-check *args:
    uv run mypy python/konfy {{ args }}
