alias b := test
alias t := test
alias c := test
alias f := test

build:
    uv build

test *args:
    uv run pytest test {{ args }}

fix *args:
    uv run ruff check --fix --show-fixes src test {{ args }}

check *args:
    uv run ruff check src test {{ args }}
