name: Docs

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: x86_64-unknown-linux-musl
          components: rustfmt, rust-src

      - name: Build Documentation
        run: cargo doc --all --no-deps  --target x86_64-unknown-linux-musl
