[workspace]

members = [
    "bricks",
    "brickster",
    "clikit",
    "elgato",
    "exercism",
    "formats",
    "game-of-life",
    "newton",
    "nordic",
    "nostd",
    "preidolia",
    "protocols",
    "tobytes",
    "xxd",
]
