FROM fedora:43

RUN dnf update
RUN dnf install -y passwd sudo openssh-server python

RUN useradd -m -s /bin/bash nc && \
    echo "user:userpw" | chpasswed && \
    echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user

RUN ssh-keygen -A
RUN sed -ii 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/ssh_config
RUN sed -ri 's/UsePAM yes/UsePAM yes/g' /etc/ssh/ssh_config

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
